### ISSUE TITLE
make explicit the version of tools we rely upon

### ISSUE THREAD

**Issue by MHBauer** [cloudfoundry-incubator/blockhead#29]
non-exhaustive list:
 - dep
 - counterfeiter
Do we have or want static analysis?
 - gometalinter
 - goimports

**Comment by nimakaviani** [comment]
https://github.com/cloudfoundry-incubator/blockhead/pull/47 makes an attempt in fixating the versions for the tools / libraries we use.

**Comment by nimakaviani** [comment]
we added tests to make sure we check node versions for consistency
610bb65c47bff6508d1473127b0d8f74bc38d7bb
