### ISSUE TITLE
fix travis reference for the tests

### ISSUE THREAD

**Issue by nimakaviani** [cloudfoundry-incubator/blockhead#3]
After changing the repo, travis is still pointing to `jberkhahn/blockhead` and needs to be updated.

Same for the reference to the repo in the badge.

**Comment by MHBauer** [comment]
![screenshot from 2018-08-08 15-30-57](https://user-images.githubusercontent.com/13337345/43867930-19674800-9b20-11e8-9b41-4cb76011e343.png)

@nimakaviani no permissions here. Does CF provide a CI runner we can use?

**Comment by MHBauer** [comment]
![screenshot from 2018-08-08 16-58-59](https://user-images.githubusercontent.com/13337345/43870447-600479a2-9b2c-11e8-9c71-da7a168ddd3f.png)


![screenshot from 2018-08-08 16-58-23](https://user-images.githubusercontent.com/13337345/43870434-4fc817c4-9b2c-11e8-88dd-f3001183edf4.png)

task completed. Closing
